<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/third_push.proto

namespace ThirdPush;

use UnexpectedValueException;

/**
 *跳转动作
 *
 * Protobuf type <code>thirdPush.ActionType</code>
 */
class ActionType
{
    /**
     *打开activity
     *
     * Generated from protobuf enum <code>ACTIVITY = 0;</code>
     */
    const ACTIVITY = 0;
    /**
     *打开
     *
     * Generated from protobuf enum <code>WEB = 1;</code>
     */
    const WEB = 1;
    /**
     *打开指定页 推荐
     *
     * Generated from protobuf enum <code>INTENT = 2;</code>
     */
    const INTENT = 2;

    private static $valueToName = [
        self::ACTIVITY => 'ACTIVITY',
        self::WEB => 'WEB',
        self::INTENT => 'INTENT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

