<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/third_push.proto

namespace ThirdPush;

use UnexpectedValueException;

/**
 *推送app
 *
 * Protobuf type <code>thirdPush.APP</code>
 */
class APP
{
    /**
     *坐席端
     *
     * Generated from protobuf enum <code>SEAT_APP = 0;</code>
     */
    const SEAT_APP = 0;
    /**
     *访客端
     *
     * Generated from protobuf enum <code>MALL_APP = 1;</code>
     */
    const MALL_APP = 1;

    private static $valueToName = [
        self::SEAT_APP => 'SEAT_APP',
        self::MALL_APP => 'MALL_APP',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

