<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/third_push.proto

namespace ThirdPush;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>thirdPush.AppList</code>
 */
class AppList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.thirdPush.APP app = 1;</code>
     */
    protected $app = 0;
    /**
     * Generated from protobuf field <code>repeated .thirdPush.Users users = 2;</code>
     */
    private $users;
    /**
     *动作
     *
     * Generated from protobuf field <code>.thirdPush.Action action = 3;</code>
     */
    protected $action = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $app
     *     @type \ThirdPush\Users[]|\Google\Protobuf\Internal\RepeatedField $users
     *     @type \ThirdPush\Action $action
     *          动作
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\ThirdPush::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.thirdPush.APP app = 1;</code>
     * @return int
     */
    public function getApp()
    {
        return $this->app;
    }

    /**
     * Generated from protobuf field <code>.thirdPush.APP app = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setApp($var)
    {
        GPBUtil::checkEnum($var, \ThirdPush\APP::class);
        $this->app = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .thirdPush.Users users = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUsers()
    {
        return $this->users;
    }

    /**
     * Generated from protobuf field <code>repeated .thirdPush.Users users = 2;</code>
     * @param \ThirdPush\Users[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUsers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \ThirdPush\Users::class);
        $this->users = $arr;

        return $this;
    }

    /**
     *动作
     *
     * Generated from protobuf field <code>.thirdPush.Action action = 3;</code>
     * @return \ThirdPush\Action
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     *动作
     *
     * Generated from protobuf field <code>.thirdPush.Action action = 3;</code>
     * @param \ThirdPush\Action $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkMessage($var, \ThirdPush\Action::class);
        $this->action = $var;

        return $this;
    }

}

