<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/third_push.proto

namespace ThirdPush;

use UnexpectedValueException;

/**
 *推送渠道
 *
 * Protobuf type <code>thirdPush.Channel</code>
 */
class Channel
{
    /**
     *腾讯TPNS推送
     *
     * Generated from protobuf enum <code>TPNS = 0;</code>
     */
    const TPNS = 0;
    /**
     *极光推送
     *
     * Generated from protobuf enum <code>JPUSH = 1;</code>
     */
    const JPUSH = 1;

    private static $valueToName = [
        self::TPNS => 'TPNS',
        self::JPUSH => 'JPUSH',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

