<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/third_push.proto

namespace ThirdPush;

use UnexpectedValueException;

/**
 * Protobuf type <code>thirdPush.Env</code>
 */
class Env
{
    /**
     *测试环境
     *
     * Generated from protobuf enum <code>DEV = 0;</code>
     */
    const DEV = 0;
    /**
     *预生产环境
     *
     * Generated from protobuf enum <code>PRE = 1;</code>
     */
    const PRE = 1;
    /**
     *生产环境
     *
     * Generated from protobuf enum <code>PROD = 2;</code>
     */
    const PROD = 2;

    private static $valueToName = [
        self::DEV => 'DEV',
        self::PRE => 'PRE',
        self::PROD => 'PROD',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

