<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/third_push.proto

namespace ThirdPush;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *请求参数
 *
 * Generated from protobuf message <code>thirdPush.Params</code>
 */
class Params extends \Google\Protobuf\Internal\Message
{
    /**
     *推送标题
     *
     * Generated from protobuf field <code>string title = 1;</code>
     */
    protected $title = '';
    /**
     *内容说明
     *
     * Generated from protobuf field <code>string content = 2;</code>
     */
    protected $content = '';
    /**
     *扩展参数
     *
     * Generated from protobuf field <code>string extra = 3;</code>
     */
    protected $extra = '';
    /**
     *指定铃声
     *
     * Generated from protobuf field <code>string sound = 4;</code>
     */
    protected $sound = '';
    /**
     *推送app列表
     *
     * Generated from protobuf field <code>repeated .thirdPush.AppList app_list = 5;</code>
     */
    private $app_list;
    /**
     *指定渠道 默认TPNS
     *
     * Generated from protobuf field <code>.thirdPush.Channel channel = 6;</code>
     */
    protected $channel = 0;
    /**
     *环境 默认dev
     *
     * Generated from protobuf field <code>.thirdPush.Env env = 7;</code>
     */
    protected $env = 0;
    /**
     *推送目标
     *
     * Generated from protobuf field <code>string audience = 8;</code>
     */
    protected $audience = '';
    /**
     *消息类型 TPNS有效
     *
     * Generated from protobuf field <code>string message_type = 9;</code>
     */
    protected $message_type = '';
    /**
     *指定推送平台
     *
     * Generated from protobuf field <code>.thirdPush.Platform platform = 10;</code>
     */
    protected $platform = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $title
     *          推送标题
     *     @type string $content
     *          内容说明
     *     @type string $extra
     *          扩展参数
     *     @type string $sound
     *          指定铃声
     *     @type \ThirdPush\AppList[]|\Google\Protobuf\Internal\RepeatedField $app_list
     *          推送app列表
     *     @type int $channel
     *          指定渠道 默认TPNS
     *     @type int $env
     *          环境 默认dev
     *     @type string $audience
     *          推送目标
     *     @type string $message_type
     *          消息类型 TPNS有效
     *     @type int $platform
     *          指定推送平台
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\ThirdPush::initOnce();
        parent::__construct($data);
    }

    /**
     *推送标题
     *
     * Generated from protobuf field <code>string title = 1;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     *推送标题
     *
     * Generated from protobuf field <code>string title = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     *内容说明
     *
     * Generated from protobuf field <code>string content = 2;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     *内容说明
     *
     * Generated from protobuf field <code>string content = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;

        return $this;
    }

    /**
     *扩展参数
     *
     * Generated from protobuf field <code>string extra = 3;</code>
     * @return string
     */
    public function getExtra()
    {
        return $this->extra;
    }

    /**
     *扩展参数
     *
     * Generated from protobuf field <code>string extra = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setExtra($var)
    {
        GPBUtil::checkString($var, True);
        $this->extra = $var;

        return $this;
    }

    /**
     *指定铃声
     *
     * Generated from protobuf field <code>string sound = 4;</code>
     * @return string
     */
    public function getSound()
    {
        return $this->sound;
    }

    /**
     *指定铃声
     *
     * Generated from protobuf field <code>string sound = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSound($var)
    {
        GPBUtil::checkString($var, True);
        $this->sound = $var;

        return $this;
    }

    /**
     *推送app列表
     *
     * Generated from protobuf field <code>repeated .thirdPush.AppList app_list = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAppList()
    {
        return $this->app_list;
    }

    /**
     *推送app列表
     *
     * Generated from protobuf field <code>repeated .thirdPush.AppList app_list = 5;</code>
     * @param \ThirdPush\AppList[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAppList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \ThirdPush\AppList::class);
        $this->app_list = $arr;

        return $this;
    }

    /**
     *指定渠道 默认TPNS
     *
     * Generated from protobuf field <code>.thirdPush.Channel channel = 6;</code>
     * @return int
     */
    public function getChannel()
    {
        return $this->channel;
    }

    /**
     *指定渠道 默认TPNS
     *
     * Generated from protobuf field <code>.thirdPush.Channel channel = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setChannel($var)
    {
        GPBUtil::checkEnum($var, \ThirdPush\Channel::class);
        $this->channel = $var;

        return $this;
    }

    /**
     *环境 默认dev
     *
     * Generated from protobuf field <code>.thirdPush.Env env = 7;</code>
     * @return int
     */
    public function getEnv()
    {
        return $this->env;
    }

    /**
     *环境 默认dev
     *
     * Generated from protobuf field <code>.thirdPush.Env env = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setEnv($var)
    {
        GPBUtil::checkEnum($var, \ThirdPush\Env::class);
        $this->env = $var;

        return $this;
    }

    /**
     *推送目标
     *
     * Generated from protobuf field <code>string audience = 8;</code>
     * @return string
     */
    public function getAudience()
    {
        return $this->audience;
    }

    /**
     *推送目标
     *
     * Generated from protobuf field <code>string audience = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setAudience($var)
    {
        GPBUtil::checkString($var, True);
        $this->audience = $var;

        return $this;
    }

    /**
     *消息类型 TPNS有效
     *
     * Generated from protobuf field <code>string message_type = 9;</code>
     * @return string
     */
    public function getMessageType()
    {
        return $this->message_type;
    }

    /**
     *消息类型 TPNS有效
     *
     * Generated from protobuf field <code>string message_type = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageType($var)
    {
        GPBUtil::checkString($var, True);
        $this->message_type = $var;

        return $this;
    }

    /**
     *指定推送平台
     *
     * Generated from protobuf field <code>.thirdPush.Platform platform = 10;</code>
     * @return int
     */
    public function getPlatform()
    {
        return $this->platform;
    }

    /**
     *指定推送平台
     *
     * Generated from protobuf field <code>.thirdPush.Platform platform = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setPlatform($var)
    {
        GPBUtil::checkEnum($var, \ThirdPush\Platform::class);
        $this->platform = $var;

        return $this;
    }

}

