<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/third_push.proto

namespace ThirdPush;

use UnexpectedValueException;

/**
 * Protobuf type <code>thirdPush.UserType</code>
 */
class UserType
{
    /**
     *客户
     *
     * Generated from protobuf enum <code>MEMBER = 0;</code>
     */
    const MEMBER = 0;
    /**
     *客服
     *
     * Generated from protobuf enum <code>KEFU = 1;</code>
     */
    const KEFU = 1;
    /**
     *后台管理
     *
     * Generated from protobuf enum <code>MANAGER = 2;</code>
     */
    const MANAGER = 2;

    private static $valueToName = [
        self::MEMBER => 'MEMBER',
        self::KEFU => 'KEFU',
        self::MANAGER => 'MANAGER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

