<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/third_push.proto

namespace ThirdPush;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>thirdPush.Users</code>
 */
class Users extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.thirdPush.UserType type = 1;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>repeated string im_id = 2;</code>
     */
    private $im_id;
    /**
     * Generated from protobuf field <code>repeated int32 id = 3;</code>
     */
    private $id;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $im_id
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\ThirdPush::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.thirdPush.UserType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.thirdPush.UserType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \ThirdPush\UserType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string im_id = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getImId()
    {
        return $this->im_id;
    }

    /**
     * Generated from protobuf field <code>repeated string im_id = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setImId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->im_id = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 id = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>repeated int32 id = 3;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->id = $arr;

        return $this;
    }

}

